name: music_player
description: A simple, full-featured local music player.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.40
  file_picker: 8.1.2
  provider: ^6.1.2
  audio_metadata_reader: ^1.8.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
